# Generated by Django 3.1.2 on 2020-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], null=True),
        ),
    ]
