# Generated by Django 3.1.2 on 2020-11-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'other')], null=True),
        ),
    ]
