# Generated by Django 3.1.2 on 2020-11-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201115_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], null=True),
        ),
    ]
