# Generated by Django 3.1.2 on 2020-11-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201115_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street_address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street_address2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
