# Generated by Django 3.1.2 on 2020-11-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_auto_20201123_1841'),
        ('profiles', '0025_auto_20201120_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
