# Generated by Django 3.1.2 on 2020-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearpayment',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
