# Generated by Django 3.1.2 on 2020-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_yearpayment_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearpayment',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
