# Generated by Django 3.1.2 on 2020-11-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201127_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearpayment',
            old_name='town_or_city',
            new_name='city',
        ),
    ]
