# Generated by Django 3.1.2 on 2020-11-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20201128_0850'),
        ('payment', '0005_yearpayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
