# Generated by Django 3.1.2 on 2020-10-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=254)),
                ('postal_code', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('energy_label', models.CharField(blank=True, max_length=254, null=True)),
                ('m2', models.IntegerField(blank=True, null=True)),
                ('m3', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.type')),
            ],
        ),
    ]
