# Generated by Django 3.1.2 on 2020-11-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20201104_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='type',
            new_name='house_type',
        ),
    ]
