# Generated by Django 3.1.2 on 2020-11-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20201104_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
