# Generated by Django 3.1.2 on 2020-11-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20201104_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='house_type',
            new_name='type',
        ),
    ]
