# Generated by Django 3.1.2 on 2020-11-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20201104_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
    ]
