# Generated by Django 3.1.2 on 2020-11-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20201104_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
