# Generated by Django 3.1.2 on 2020-11-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
