# Generated by Django 3.1.2 on 2020-11-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20201104_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
