# Generated by Django 3.1.2 on 2020-11-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20201105_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='type',
            new_name='house_type',
        ),
    ]
