# Generated by Django 3.1.2 on 2020-11-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20201105_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='houses.city'),
            preserve_default=False,
        ),
    ]
