# Generated by Django 3.1.2 on 2020-11-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_auto_20201123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='houses.type'),
            preserve_default=False,
        ),
    ]
